# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands:
  install-package:
    steps:
      - checkout
      - run:
          name: Installing package
          command: pip install .

jobs:
  tests:
    docker:
      - image: cimg/python:3.13
    steps:
      - install-package
      - run:
          name: Running tests
          command: python -m unittest discover tests

  lint:
    docker:
      - image: cimg/python:3.13
    steps:
      - install-package
      - run:
          name: Installing optional requirements
          command: pip install -r requirements-dev.txt
      - run:
          name: Running linter
          command: python -m ruff check

workflows:
  version: 2
  ruby-3.13:
    jobs:
      - tests
      - lint
