# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Installing package
          command: pip install .
      - run:
          name: Running tests
          command: python -m unittest tests

workflows:
  version: 2
  ruby-3.13:
    jobs:
      - tests
